project: miniav
default_services: 
  - dev
  - vnc
services:
  dev:
    build:
      args:
        APT_DEPENDENCIES: "bash zsh vim git git-lfs python3-pip python3-tk"
        PIP_REQUIREMENTS: "wa_simulator pandas matplotlib numpy>=1.19 opencv-python tornado black Pillow torch torchvision"
  vnc:
    build:
      args:
        VNC_PASSWORD: ""
