ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    sensor_timeout: 0.1
    two_d_mode: false
    
    odom_frame: 'odom'
    base_link_frame: 'base_link'
    world_frame: 'odom'

    imu0: /sbg/imu_data
    imu0_config: [false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, true,
                  false, false, false]
    imu0_queue_size: 10
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false

