ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    
  
    two_d_mode: false
    publish_tf: true
    frequency: 30.0
    sensor_timeout: 0.5
    transform_timeout: 0.0
    two_d_mode: true

    base_link_frame: "imu_link" #simulation
    #base_link_frame: "imu" #reality

    
    imu0: "/sensing/imu/data" #simulation
    #imu0: "/imu" #reality
    imu0_config: [false, false, false,
              false, false, true,
              false, false, false,  # Set velocity components to false
              false, false, true,
              true, true, false]

    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
